apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dranet.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dranet.labels" . | nindent 4 }}
